### ISSUE TITLE
Multiline support for TODO Highlighter

### ISSUE THREAD

**Issue by techmagus** [willasm/project-notes#1]
Hi,

Is it possible to add multi-line support? Or, how do I make it work? Here's a sample:

```go
{{/*
  TODO:
  NOTE: 
  FIXME: 
  REVIEW: 
  CHANGED: 
  !word
  @word
  #word
  $word
*/}}
```

It is in Go-style commenting in an HTML file. It is the preferred commenting style for Hugo layout/template files. I tried both `{{/* */}}` and `{{- /* */ -}}` but to no avail. It works fine if it is single line like:

```go
{{/* Changed: */}}

{{- /* Review: */ -}}

{{- /* Idea: */}}

{{/* Research: */ -}}
```

Versions:
* Extension: TODO Highlighter
* Current version: v0.0.5
* VSCode: 1.65.2

Thank you. Shalom!

**Comment by willasm** [comment]
Technically it should work with any language comments that vscode recognizes as a comment. I'm actually in the middle of doing a major update to the extension. I am switching from using text-mate rules to using text decorations. This will allow for much more control over the highlighting. In the meantime here is something you can try.
Locate the extensions folder "willasm.project-notes-0.0.5" in your User folder "%USERPROFILE%\.vscode\extensions" and open the "package.json" file in any editor. Under the "grammars" section you will see...

"grammars": [
	{
		"path": "./syntaxes/project-notes.tmGrammar.json",
		"scopeName": "project-notes.injection",
		"injectTo": [
			"source",
			"text.html",
			"source.vue",
			"source.tbscript"
		],

In the section "injectTo": you can try adding the line "source.go" below "source.tbscript", (Don't forget a comma after "source.tbscript"). You will need to restart vscode after saving the file. The only other thing I can think of is to add  "source.html" as well, although that should not be needed because of the line "text.html". Please let me know if that works or not.

With the next update it will possible to define your own regular expressions for comments for any language you use which will eliminate any problems like this. Hopefully I will have a release version completed some time this week.
Here is a sneak peak of where I'm at with the upcoming update.. (As you can see the highlighting is basically done.)



![2022-03-18 12_24_03- Extension Development Host  - ScreenShot](https://user-images.githubusercontent.com/94352899/159063496-58af31a0-d120-464e-8ccc-da48f189e5ce.png)

Edit: Are you using an extension for Hugo syntax highlighting? If so it may be the cause of the problem. I wrote a language extension a while ago and it had problems with this extension as I had not defined comments properly. The comments looked fine in vscode for my language extension the way I had them defined but this extension was not working until I changed how I was defining them. Let me know what extension you are using and I'll take a look at it. It is a relatively easy fix to ensure that the comments are defined properly.

**Comment by techmagus** [comment]
Hi, just a quick update: I tried the source.go and source.html but did not work after restarting. I also disabled all extensions.

I'll try it again later with a fresh settings and workspace, and test files. I'll post an update then.

Thank you again. Shalom!

**Comment by willasm** [comment]
I still think it is the extension you are using for Go-style language support. My extension will not work at all with that disabled. My extension requires that the language support extension defines the comments correctly. This is defined in the languages tmLanguage.json file. Are you using "Hugo Language and Syntax Support" by budparr? I have looked at the code for that extension and can confirm he has defined comments the easy way. (The same way I originally did for my first language extension) and that causes the problem. Where he has a very basic regex setup for comments...

    {
      "begin": "{{\\/\\*|{{- \\/\\*",
      "end": "\\*\\/}}|\\*\\/ -}}",
      "name": "comment.block.hugo"
    },

It should look more like this... (Taken from my tbscript language extension)

        "comments": {
            "begin": "(^[ \\t]+)?(?=//)",
            "beginCaptures": {
                "1": {
                    "name": "comment.line.double-slash.tbscript"
                }
            },
            "end": "(?!\\G)",
            "patterns": [{
                "begin": "//",
                "beginCaptures": {
                    "0": {
                        "name": "comment.line.double-slash.tbscript"
                    }
                },
                "end": "\\n",
                "name": "comment.line.double-slash.tbscript"
            }]
        },

I originally had a very similar comments definition in my language extension and my syntax highlighter extension would not work until I changed the comments section to what you see above...

At any rate I'm close to releasing the next update. I have single line comments done for 18 different file extensions including HTML. Still need to add the multi line comments code though.. Here is a preview shot you may like...
![2022-03-22 08_53_51- Extension Development Host  - Screenshot2](https://user-images.githubusercontent.com/94352899/159519885-f97d24fd-1d10-4950-8ef6-1cb5c7aada53.png)

**Comment by willasm** [comment]
I installed "Hugo Language and Syntax Support" by budparr and it does indeed appear there is a bug somewhere in my extension regarding multi-line comments. I am not going to spend too much more time on this as the updated version will correct this problem and I'm close to completing it now. The new versions code is basically a complete re-write of the extension so working on the earlier branch would be pointless at this point in time. My apologies to you but I promise the new version will be worth the wait.

**Comment by techmagus** [comment]
Hi, tried it again with fresh settings (or clean settings.json), new workspace,  and without any extensions, I can't make it to work.

> I still think it is the extension you are using for Go-style language support. My extension will not work at all with that disabled. My extension requires that the language support extension defines the comments correctly.

Ahhh. I re-enabled the Go extension (v0.32.0) from the Go Team and restarted, didn't work either.

> Are you using "Hugo Language and Syntax Support" by budparr?

Nope, I haven't tried.

> My apologies to you but I promise the new version will be worth the wait.

No worries and no rush. More than happy to wait. :)

Thank you again, Shalom!

**Comment by willasm** [comment]
Just wanted to let you know I have uploaded the new version to Github. It may be a few more days until I upload the new version to the Marketplace as I still want to add a few more filename extensions to the settings file and make some other minor additions. The syntax highlighting is working great though and multiline comments are working correctly. If you want to try the new version you can download from the releases folder 'project-notes-0.0.6.vsix' and install it manually. (Choose install from vsix in the extensions sidebar dropdown menu - the 3 ...) Uninstall the current version first though. I suggest reading the new documentation as well as the number of changes is significant. Have a good week, William.

**Comment by willasm** [comment]
Will be uploading v1.0.0 to the Marketplace soon. Many new features added. See the documentation for details.

**Comment by techmagus** [comment]
Hi,

Thank you very much. I got the v1 update and it's working perfectly. ^_^

**Comment by willasm** [comment]
That is what I like to hear!
