### ISSUE TITLE
New global file not saving in custom location

### ISSUE THREAD

**Issue by sanihaq** [willasm/project-notes#3]
After setting new global notes location. creating new file still uses the old(default) location. Creating new file (from outside) in new locations loads correctly (after reload).

Additional Suggestion: 

- use existing user location as default global location. (e.g. C:\Users\<username>\Notes) 
- place some example notes file describing projects-notes use cases features and for quick overview
- for "Project notes" (i.e. local notes) .vscode folder should be left alone. instead use a new folder (customizable by user)
- It'd be good practice to have a file watcher so changes to folder from outside of vscode load automatically.

**Comment by willasm** [comment]
Thanks for your help again sanihaq. At some point while testing I had hard coded the global notes folder location on one line of code and forgot to remove that. Very bad bug to leave in there so big thanks for bringing that to my attention. The fix for this has been uploaded.

Originally I had used a folder in the users home location as that made more sense to me. It however was suggested to me to use the extensions global storage location instead which is there for the purpose of storing the extensions data files. I'm still on the fence on that so may just revert back to defaulting to the users home folder. That was the entire reason why I added the option to select a default folder location (which starts in the users home folder) for global notes so the end user can choose their preferred location.

Example notes is an excellent suggestion, will do that.

A dedicated folder for local notes was my original plan but after much thought I felt a lot of people probably would not like an extension creating new folders within their project root folder. As most projects already have a .vscode folder anyways it made sense at the time to just use that. However the suggestion of adding an option for the local folder location is an excellent idea and I will definitely add that.

Adding a file watcher is already high on my todo list.

Thanks again for all your help and suggestions, William

**Comment by sanihaq** [comment]
You're welcome @willasm 
For global default location, it'd be better to use user "Document" folder with specific folder name (e.g. for windows `C:\Users\Sani\Documents\MyNotes`)
My reasoning behind not using `.vscode` is similar to the reason you mentioned for global folder.` .vscode` folder is specifically made for "vscode" related files. Notes files had nothing to do with vscode. It just uses vscode to edit along with this extension. therefore, it shouldn't be used here. Users who are using this extension should already know creating notes file using this extension will place file in a specific location. The folder should only be created when the user creates a note for the first time.

**Comment by willasm** [comment]
Thanks again for your input. I have already changed the local notes folder to "notes" by default and added a command to allow the user to change the folder name to whatever they choose from within vscode. Setting the global notes folder is a little more challenging. I can use `os.homedir()`, which works across all platforms, to get the users home folder without any problems. To get the 'Documents' folder is the problem. Every example I have found simply appends 'Documents' to that but that is not a reliable method at all as the user change the location easily. Just right click on your Documents folder and you will see a tab 'location' which allows you to move the documents folder to wherever you want. I have done this myself with my download folder which I have moved to my D drive. So unless I can find a reliable cross platform method of getting the documents folder  my only other option is to create the notes folder in the home directory. This seems to be the method a lot of programs use  from what I see in my home folder.

Anyhow with these changes I will need to update the documentation as well but I should have the next update uploaded after I have that done, William

**Comment by coswvw** [comment]
Thank you for your work! I'm using this plugin and suggest that it should allow users to customize where project notes are stored instead of .vscode right now, which is the most pressing need at this moment. There is another similar plugin in the market, named Notes, which also has the issue of not providing a user-definable storage location for local project notes. Moreover, the relative path (e.g., "/.notes") or using VS Code's variables like "${workspaceFolder}/.notes" is suggested. I believe that if this is improved, more and more people would like to use this plugin, as the plugin's function is actually a very pressing need in VS Code's Markdown. As for other suggestions, maybe further beautify the icon in the sidebar. Thanks again, expect the next version.

**Comment by willasm** [comment]
Sorry for not updating this for such a long time, just been too busy. Version 1.5.0 has just been uploaded to the marketplace and should be available for updating shortly.

- Local Notes now default to `.pnotes` folder
- Global Notes now default to `.pnotes` folder in the users home directory.
- Added the command `Project Notes: Set Local Notes Folder Name`
- Added file system watchers for both Local and Global note folders

Still need to make improvements to the documentation. Plan to add a `Project Notes - Quick Tips.md` file to be added into the Global Notes folder on future updates. Thanks for all the valuable suggestions. Leaving this thread open for now in case anyone has more suggestions.. Thank you, William.

**Comment by sanihaq** [comment]
I guess the next big thing would be to add backup and sync ( via git or other e.g. gdrive etc )
